{% set name = "opentracing_instrumentation" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d94801aebab95b7e8f3eeb80ee0e5e886ad4f1761bcadff9b5d1d3d04560c04a

build:
  number: 2
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future
    - futures  # [py2k]
    - wrapt
    - tornado >=4.1,<6
    - contextlib2
    - opentracing >=2,<3
    - six

test:
  imports:
    - opentracing_instrumentation
    - opentracing_instrumentation.client_hooks

about:
  home: https://github.com/uber-common/opentracing-python-instrumentation
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tracing Instrumentation using OpenTracing API (http://opentracing.io)
  dev_url: https://github.com/uber-common/opentracing-python-instrumentation

extra:
  recipe-maintainers:
    - nehaljwani
