appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: NMCFNCfCVQt2FXYejDmar3DdThHGN89eIhdsGfoIXnQpiv34jQVai8qEBYpHbkRi44TUqpJVo1oFJlulo66s4ChVgDIe53Ll4JZl84L/SVT8F4CmFqe6NBkSpVaYWpVLN+CtnBrf5ZK9SE0wyTrmXgAdQ9obyJe/NPEdejoVUa3ddqKuV6ER3BYg80w/xwNPPUXkTNvURawH0HQMCf1Nfx9hNal/9qjK3p8h16a+URINi83uVPzHEl18Rr5Ld701qN9TPdcB0CXIP67spmDKzgr3O9vMem5iWgGtI/Arnw4wpmCglxluWx+9RkwI/bcmG02CrA7WEVm0lFsaCaxHh+HQ7jUdneh3phynpcfRMWOlgc4x5NGFvQpO6cAxzNKpSel4FGYOyylPPh3Yo8ae6stPNiMmMWTynxU90eTPJ1EA/v5eLlQwZzlbWGYWw2MNxYWH3djkwqEWHtM7qbUu7GbQ7RmAaMS67MWaGSZXlAtYDdRlnzb7y1ZSXUBPMmOQjrvCzx4iayByDgGR8FB1pC0tyEgTs0JqHDLC5rWiMZKtQAvQC3Av9cnmGkg7Ha0S+oMT5mmQHPtl1iGJkl8T0UqsV+8Uy8WDQwP0gXSKo6m4bONQKk26YQmDUzIbIpn16kFZ/UtMKJuZBh3jIUFLXXxqjnegrAZJNsB2pPLfDKw=}
provider:
  win: azure
conda_forge_output_validation: true
